name: CICD

# on:
#   push:
#     branches: [main]
#     paths-ignore:
#       - '**.md'
#   pull_request:
#     paths-ignore:
#       - '**.md'

on:
  workflow_dispatch: 
    

jobs:
   continous-Integration-continous-Deployment:
     uses: ./.github/workflows/ci.yml  
     secrets: inherit
