name: CICD

on:
  push:
    branches: [main]
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
    

jobs:
   continous-Integration-continous-Deployment:
     uses: ./.github/workflows/ci.yml  
  
