 #Goal: build the image for devboard frontend and push to docker hub

name: CI

on:
  push:
    branches: [main]

jobs:
    frontend:
      runs-on: ubuntu-latest
      steps:
       - name: code checkout
         uses: actions/checkout@v7

       - name: setup nodesjs
         uses: actions/setup-node@v6
         with:
          node-version: '26'
          cache: npm
          cache-dependency-path: frontend/package-lock.json

       - name:  install npm packages
         run: npm ci --legacy-peer-deps
         working-directory: frontend

       - name: run linter
         run: npm run lint
         working-directory: frontend

       - name: run tests
         run: npm run test
         working-directory: frontend  

       - name: docker login
         uses: docker/login-action@v4
         with:
            username: ${{ vars.DOCKERHUB_USERNAME}}
            password: ${{ secrets.DOCKERHUB_TOKEN}}

       - name: docker build and push
         uses: docker/build-push-action@v7
         with:
            context: ./frontend
            push: true
            tags: ${{ vars.DOCKERHUB_USERNAME}}/devboard-frontend-actions:latest



    backend:
      runs-on: ubuntu-latest
      steps:
       - name: code checkout
         uses: actions/checkout@v7

       - name: setup go
         uses: actions/setup-go@v6
         with:
          go-version: '1.23'
          go-version-file: 'go.mod'
          cache-dependency-path: go.sum

       - name:  run go formatter
         run: go fmt
         working-directory: backend

       - name: run go vet
         run: go vet
         working-directory: backend

       - name: run tests
         run: go test
         working-directory: backend

       - name: docker login
         uses: docker/login-action@v4
         with:
            username: ${{ vars.DOCKERHUB_USERNAME}}
            password: ${{ secrets.DOCKERHUB_TOKEN}}

       - name: docker build and push
         uses: docker/build-push-action@v7
         with:
            context: ./backend
            push: true
            tags: ${{ vars.DOCKERHUB_USERNAME}}/devboard-backend-actions:latest
