name: docker_scan

on:
  workflow_call:

jobs:
  docker_file_lint_and_scan:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: fail
      matrix:
        folder: ['frontend','backend']
    steps:
      - name: code checkout
        uses: actions/checkout@v7
      
      - name: ${{ matrix.folder }} Dockerfile lint
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: ${{ matrix.folder}}/Dockerfile

      - name: docker login
        uses: docker/login-action@v4
        with:
          username: ${{ vars.DOCKERHUB_USERNAME}}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: docker build  ${{ matrix.folder } image
        run: docker build -t ${{ vars.DOCKERHUB_USERNAME }}/devboard-${{ matrix.folder }}:latest .
        workking-directory: ${{ matrix.folder }}

      - name: Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@v0.36.0
        continue-on-error: true
        with:
          image-ref: ${{ vars.DOCKERHUB_USERNAME }}/devboard-${{ matrix.folder }}:latest
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severtity: "CRITICAL"