name: auto Linter # check the syntax.format,indentation

on:
  push:
    paths: "*.py"
  workflow_dispatch: 

jobs:
  code:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the code
        uses: actions/checkout@v7  # this will automatically clone

      - name: install linter
        run: pip install ruff #install the linting tool

      - name: check the files for linting
        run: ruff check .
    
