name: Secrets_Scanning

on:
  workflow_call:

jobs:
  secrets_scan:
    runs-on: ubuntu-latest
    steps:
      - name: code checkout
        uses: checkout/action@v7
        with:
          fetch-depth: 0  

      - name: GIT leaks scanner
        uses: gitleaks/gitleaks_action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}   